from __future__ import annotations

from typing import Awaitable, Callable, Protocol

from g3ku.core.messages import UserInputMessage
from g3ku.core.results import RunResult
from g3ku.core.state import AgentState


class AgentSession(Protocol):
    @property
    def state(self) -> AgentState: ...

    def subscribe(
        self,
        listener: Callable[[object], Awaitable[None] | None],
    ) -> Callable[[], None]: ...

    async def prompt(self, message: str | UserInputMessage) -> RunResult: ...
    async def continue_(self) -> RunResult: ...

    def steer(self, message: str | UserInputMessage) -> None: ...
    def follow_up(self, message: str | UserInputMessage) -> None: ...

    async def pause(self) -> None: ...
    async def resume(self, *, replan: bool = False, additional_context: str | None = None) -> RunResult: ...
    async def cancel(self, *, reason: str = "user_cancelled") -> None: ...

    def set_model(self, model: str) -> None: ...
    def set_reasoning_effort(self, level: str | None) -> None: ...

