from __future__ import annotations

from .enums import AuthMode, Capability, ProtocolAdapter
from .models import ProviderTemplate
from .template_builders import (
    build_anthropic_compatible_template,
    build_gemini_template,
    build_ollama_template,
    build_openai_compatible_template,
)


PROVIDER_TEMPLATES: list[ProviderTemplate] = [
    build_openai_compatible_template(
        provider_id="custom",
        display_name="Custom OpenAI-Compatible",
        default_base_url="http://localhost:8000/v1",
        default_model="custom-model",
        suggested_models=["custom-model"],
        category="custom-compatible",
        default_api_mode=ProtocolAdapter.CUSTOM_DIRECT,
    ),
    build_openai_compatible_template(
        provider_id="openai",
        display_name="OpenAI",
        default_base_url="https://api.openai.com/v1",
        default_model="gpt-4.1",
        suggested_models=["gpt-4.1", "gpt-4o", "gpt-4o-mini", "gpt-5.4"],
        default_api_mode=ProtocolAdapter.OPENAI_RESPONSES,
    ),
    build_anthropic_compatible_template(
        provider_id="anthropic",
        display_name="Anthropic",
        default_base_url="https://api.anthropic.com/v1",
        default_model="claude-sonnet-4-5",
        suggested_models=["claude-opus-4-6", "claude-sonnet-4-5"],
    ),
    build_openai_compatible_template(
        provider_id="openrouter",
        display_name="OpenRouter",
        default_base_url="https://openrouter.ai/api/v1",
        default_model="anthropic/claude-sonnet-4-5",
        suggested_models=["anthropic/claude-sonnet-4-5", "openai/gpt-4.1", "deepseek/deepseek-chat"],
        site_metadata=True,
        category="gateway",
    ),
    build_openai_compatible_template(
        provider_id="deepseek",
        display_name="DeepSeek",
        default_base_url="https://api.deepseek.com/v1",
        default_model="deepseek-chat",
        suggested_models=["deepseek-chat", "deepseek-reasoner"],
    ),
    build_openai_compatible_template(
        provider_id="groq",
        display_name="Groq",
        default_base_url="https://api.groq.com/openai/v1",
        default_model="llama-3.3-70b-versatile",
        suggested_models=["llama-3.3-70b-versatile", "llama-3.1-8b-instant"],
    ),
    build_openai_compatible_template(
        provider_id="zhipu",
        display_name="Zhipu AI",
        default_base_url="https://open.bigmodel.cn/api/paas/v4",
        default_model="glm-4.7",
        suggested_models=["glm-5", "glm-4.7", "glm-4.7-flash"],
    ),
    build_openai_compatible_template(
        provider_id="dashscope",
        display_name="DashScope",
        default_base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        default_model="qwen-max",
        suggested_models=["qwen-max", "qwen-plus", "qwen-turbo"],
    ),
    build_openai_compatible_template(
        provider_id="vllm",
        display_name="vLLM",
        default_base_url="http://127.0.0.1:8000/v1",
        default_model="your-model-id",
        suggested_models=["your-model-id"],
        api_key_default="vllm-local",
        category="local-openai-compatible",
    ),
    build_gemini_template(
        provider_id="gemini",
        display_name="Gemini",
        default_base_url="https://generativelanguage.googleapis.com",
        default_model="gemini-2.5-pro",
        suggested_models=["gemini-2.5-pro", "gemini-2.5-flash", "gemini-1.5-pro"],
    ),
    build_openai_compatible_template(
        provider_id="moonshot",
        display_name="Moonshot",
        default_base_url="https://api.moonshot.ai/v1",
        default_model="kimi-k2.5",
        suggested_models=["kimi-k2.5", "kimi-k2-thinking", "kimi-k2-0905-preview"],
    ),
    build_openai_compatible_template(
        provider_id="minimax",
        display_name="MiniMax",
        default_base_url="https://api.minimax.io/v1",
        default_model="MiniMax-M2.5",
        suggested_models=["MiniMax-M2.5", "MiniMax-M2.5-highspeed"],
    ),
    build_openai_compatible_template(
        provider_id="aihubmix",
        display_name="AiHubMix",
        default_base_url="https://aihubmix.com/v1",
        default_model="gpt-4.1",
        suggested_models=["gpt-4.1", "claude-sonnet-4-5", "deepseek-chat"],
        category="gateway",
    ),
    build_openai_compatible_template(
        provider_id="siliconflow",
        display_name="SiliconFlow",
        default_base_url="https://api.siliconflow.cn/v1",
        default_model="Qwen/Qwen2.5-72B-Instruct",
        suggested_models=["Qwen/Qwen2.5-72B-Instruct", "deepseek-ai/DeepSeek-V3"],
        category="gateway",
    ),
    build_openai_compatible_template(
        provider_id="volcengine",
        display_name="VolcEngine",
        default_base_url="https://ark.cn-beijing.volces.com/api/v3",
        default_model="doubao-seed-1-8-251228",
        suggested_models=["doubao-seed-1-8-251228", "glm-4-7-251222", "kimi-k2-5-260127"],
        category="gateway",
    ),
    build_openai_compatible_template(
        provider_id="responses",
        display_name="OpenAI Responses",
        default_base_url="https://api.openai.com/v1",
        default_model="gpt-4.1",
        suggested_models=["gpt-4.1", "gpt-5.4"],
        default_api_mode=ProtocolAdapter.OPENAI_RESPONSES,
        category="direct",
    ),
    build_openai_compatible_template(
        provider_id="openai_codex",
        display_name="OpenAI Codex",
        default_base_url="https://chatgpt.com/backend-api",
        default_model="gpt-5.4",
        suggested_models=["gpt-5.4", "gpt-5.3-codex-spark"],
        default_api_mode=ProtocolAdapter.OAUTH_PROXY,
        auth_mode=AuthMode.OAUTH_CACHE,
        category="oauth",
        api_key_default="oauth-cache",
    ),
    build_openai_compatible_template(
        provider_id="github_copilot",
        display_name="GitHub Copilot",
        default_base_url="https://api.githubcopilot.com",
        default_model="gpt-4o-mini",
        suggested_models=["gpt-4o-mini", "claude-3.5-sonnet", "gpt-4.1"],
        default_api_mode=ProtocolAdapter.OAUTH_PROXY,
        auth_mode=AuthMode.OAUTH_CACHE,
        category="oauth",
        api_key_default="oauth-cache",
    ),
    build_ollama_template(
        provider_id="ollama",
        display_name="Ollama",
        default_base_url="http://127.0.0.1:11434",
        default_model="llama3.3",
        suggested_models=["llama3.3", "qwen2.5-coder:32b", "glm-4.7-flash"],
    ),
    build_openai_compatible_template(
        provider_id="dashscope_embedding",
        display_name="DashScope Embedding",
        default_base_url="https://dashscope.aliyuncs.com",
        default_model="qwen3-vl-embedding",
        suggested_models=["qwen3-vl-embedding"],
        category="embedding",
        default_api_mode=ProtocolAdapter.DASHSCOPE_EMBEDDING,
        capability=Capability.EMBEDDING,
    ),
    build_openai_compatible_template(
        provider_id="dashscope_rerank",
        display_name="DashScope Rerank",
        default_base_url="https://dashscope.aliyuncs.com",
        default_model="qwen3-vl-rerank",
        suggested_models=["qwen3-vl-rerank"],
        category="rerank",
        default_api_mode=ProtocolAdapter.DASHSCOPE_RERANK,
        capability=Capability.RERANK,
    ),
]

